#!/bin/bash

#
# Functions shared by all test cases.
#

# Create files in the device so them can be isolated later
create-files-in-device() {
    local FILE_ATTRS="file1|F|0600|1000:2000 \
                      dir1|D|0700|1000:0 \
                      dir1/file2|F|0660|1000.0 \
                      dir1/file3|F|0666|1000.2000 "

    for FILE_ATTR in $FILE_ATTRS
    do
        FILE_NAME=$(echo $FILE_ATTR | cut -d '|' -f 1)
        FILE_TYPE=$(echo $FILE_ATTR | cut -d '|' -f 2)
        FILE_PERM=$(echo $FILE_ATTR | cut -d '|' -f 3)
        FILE_USER=$(echo $FILE_ATTR | cut -d '|' -f 4)

        if [ $FILE_TYPE == "F" ]
        then
            device-shell-root "touch /etc/$FILE_NAME"
        else
            device-shell-root "mkdir -p /etc/$FILE_NAME"
        fi
        device-shell-root "chmod $FILE_PERM /etc/$FILE_NAME"
        device-shell-root "chown $FILE_USER /etc/$FILE_NAME"
    done
}

# Check if "filename" has the same ownership as "/workdir"
check-file-ownership-as-workdir() {
    local FILE_NAME="$1"

    local WDIR_UID=$(stat -c %u .)
    local FILE_UID=$(stat -c %u "$FILE_NAME")
    assert_equal "$WDIR_UID" "$FILE_UID"

    local WDIR_GID=$(stat -c %g .)
    local FILE_GID=$(stat -c %g "$FILE_NAME")
    assert_equal "$WDIR_GID" "$FILE_GID"
}

# Check if it's possible to remove workding output files generated by
# TorizonCore Builder
check-rm-output-file() {
    run rm -rf $@
    assert_success
}
